buildpacks = [
  { id = "org.cloudfoundry.openjdk",uri = "../../openjdk-cnb/build-out",latest = true },
  { id = "org.cloudfoundry.buildsystem",uri = "../../build-system-cnb/build-out",latest = true },
  { id = "org.cloudfoundry.jvmapplication",uri = "../../jvm-application-cnb/build-out",latest = true },
  { id = "org.cloudfoundry.myisv",uri = "../myisv-cnb/build-out",latest = true },
  { id = "org.cloudfoundry.procfile",uri = "../../procfile-cnb/build-out",latest = true },

  # { id = "io.pivotal.openjdk",uri = "../../p-openjdk-cnb/build-out",latest = true },
  # { id = "io.pivotal.buildsystem",uri = "../../p-build-system-cnb/build-out",latest = true },
  # { id = "io.pivotal.jvmapplication",uri = "../../p-jvm-application-cnb/build-out",latest = true },


]

[[groups]]
labels = [ "java" ]
buildpacks = [
  { id = "org.cloudfoundry.openjdk",                  version = "latest" },
  { id = "org.cloudfoundry.buildsystem",              version = "latest", optional = true },
  { id = "org.cloudfoundry.jvmapplication",           version = "latest", optional = true },
  { id = "org.cloudfoundry.myisv",                    version = "latest", optional = true },
  { id = "org.cloudfoundry.procfile",                 version = "latest", optional = true },
]

[stack]
id = "io.pivotal.bionic"
# build-image = "packs/build:0.1.0"
# run-image   = "packs/run:0.1.0"
build-image = "cfbuildpacks/cflinuxfs3-cnb-experimental:build"
run-image   = "cfbuildpacks/cflinuxfs3-cnb-experimental:run"
