---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: azure-application-insights-cnb

outputs:
- name: artifactory

caches:
- path: go-module-cache

run:
  path: azure-application-insights-cnb/ci/package.sh
